In [1]:
#pandas refers to panel data ,eco terms for multi-dimensional
'''
series
dataframes
missing data
merging,joining,concatination
groupby and aggregation
pivot tables and crosstab
operations
working with real data
capstone project
'''

'\nseries\ndataframes\nmissing data\nmerging,joining,concatination\ngroupby and aggregation\npivot tables and crosstab\noperations\nworking with real data\ncapstone project\n'

In [2]:
#SERIES(is one dimensional labelled array capable of holding any data type)
import numpy as np
import pandas as pd

In [5]:
labels = ['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [6]:
pd.Series(my_list)    #10,20,30 re data points and 01,2,3 are lables

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [14]:
'''combination of series called dataframe'''

'combination of series called dataframe'

In [15]:
'''
creating a dataframe
selection and indexing of columns'
creating a new column
removing column
selecting rows
selectig subsets of rows and columns
conditional selection
'''

"\ncreating a dataframe\nselection and indexing of columns'\ncreating a new column\nremoving column\nselecting rows\nselectig subsets of rows and columns\nconditional selection\n"

In [23]:
import numpy as np
import pandas as pd

In [52]:
a=np.random.randint(1,11,10)
a

array([ 6, 10,  8,  1,  3,  1,  7,  6,  3,  8], dtype=int32)

In [53]:
label=[]
for i in range(1,11):
    label.append(i)
label

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
pd.Series(a,index=label)

1      6
2     10
3      8
4      1
5      3
6      1
7      7
8      6
9      3
10     8
dtype: int32

In [55]:
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
data

{'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Age': [28, 34, 29, 42],
 'City': ['New York', 'Paris', 'Berlin', 'London'],
 'Salary': [65000, 70000, 62000, 85000]}

In [59]:
label=np.arange(1,11)
label

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#create dataframe
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [98]:
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'London',78000]
]
data_list

[['John', 28, 'New York', 65000], ['Anna', 34, 'London', 78000]]

In [100]:
df_l=pd.DataFrame(data_list)
df_l

      0   1         2      3
0  John  28  New York  65000
1  Anna  34    London  78000

In [101]:
cols=["Name","Age","City","Salary"]
df_l=pd.DataFrame(data_list,columns=cols)
df_l

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34    London   78000

In [102]:
#selection and indexing of columns
df_l["Name"]   #ek row select krne k liye

0    John
1    Anna
Name: Name, dtype: object

In [103]:
#multipe rows k liye list bnao
df_l[["Name","City"]]

   Name      City
0  John  New York
1  Anna    London

In [104]:
#creating the colmn as designation
df_l["Designation"]=["Doctor","Teacher"]
df_l    #jitni rows hai utni value dal skte

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34    London   78000     Teacher

In [106]:
#remove column
df_l.drop("City",axis = 1)

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [107]:
df_l
#ab yaha remove krne k baad bhi ni hta column toh ab ham inplace use krenge proper delete krne k liye

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34    London   78000     Teacher

In [108]:
df_l.drop("City",axis = 1,inplace= True)
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [110]:
df_l.drop(["Age","Salary"],axis = 1)

   Name Designation
0  John      Doctor
1  Anna     Teacher

In [111]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [112]:
#selecting a row(we use loc(location) for rows)
df_l.loc[0]

Name             John
Age                28
Salary          65000
Designation    Doctor
Name: 0, dtype: object

In [113]:
df_l.loc[[0,1]]

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [114]:
#selectin subset rows and columns
df.loc[[0,1]][['Age','Salary']]

   Age  Salary
0   28   65000
1   34   70000

In [116]:
df_l.loc[1]

Name              Anna
Age                 34
Salary           78000
Designation    Teacher
Name: 1, dtype: object

In [122]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [125]:
df_l.loc[[0,1]][['Name','Designation']]

   Name Designation
0  John      Doctor
1  Anna     Teacher

In [127]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [129]:
#conditional selection
#find age whose age is above 30
df_l[df_l['Age']>30]

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [133]:
#find age whose is above 20 and they designation  teacher
# '&'-Mtlb AND '|'-mtlb OR
df_l[(df_l["Age"]>20 )&( df_l["Designation"]=='Teacher')]

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [132]:
#Advanced method
df_l.query("Age > 20 and Designation == 'Teacher'")

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [1]:
'''
Finding Missing data
Removing missing data
filling the missing data
'''

'\nFinding Missing data\nRemoving missing data\nfilling the missing data\n'

In [3]:
import numpy as np
import pandas as pd

In [8]:
#nan mtln nonevalue
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [17]:
#ham true false mei dekh lenge ki her rows mei nan value hai ki nhi using 'isna'
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [18]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [19]:
#kya sb mei null vale hau?
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [20]:
'''Removing works on rows'''
df.dropna()   #jis jsi mei null value hai hata do woh row

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
#thresh
df.dropna(thresh=3)    #atleast 3 none null val honi chahiye

In [ ]:
#filling the non value data

In [21]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [22]:
df.fillna(0)    #jaha nan hai waha 0

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [23]:
values={'A':1,'B':2,'C':3,'D':4}
df.fillna(value=values)

     A    B    C    D
0  1.0  2.0  1.0  1.0
1  2.0  2.0  2.0  4.0
2  1.0  3.0  3.0  4.0
3  4.0  4.0  3.0  4.0
4  5.0  5.0  3.0  5.0

In [24]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [25]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [ ]:
#mergingJoiningConcatination