In [1]:
#pandas refers to panel data ,eco terms for multi-dimensional
'''
series
dataframes
missing data
merging,joining,concatination
groupby and aggregation
pivot tables and crosstab
operations
working with real data
capstone project
'''

'\nseries\ndataframes\nmissing data\nmerging,joining,concatination\ngroupby and aggregation\npivot tables and crosstab\noperations\nworking with real data\ncapstone project\n'

In [2]:
#SERIES(is one dimensional labelled array capable of holding any data type)
import numpy as np
import pandas as pd

In [5]:
labels = ['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [6]:
pd.Series(my_list)    #10,20,30 re data points and 01,2,3 are lables

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [14]:
'''combination of series called dataframe'''

'combination of series called dataframe'

In [15]:
'''
creating a dataframe
selection and indexing of columns'
creating a new column
removing column
selecting rows
selectig subsets of rows and columns
conditional selection
'''

"\ncreating a dataframe\nselection and indexing of columns'\ncreating a new column\nremoving column\nselecting rows\nselectig subsets of rows and columns\nconditional selection\n"

In [23]:
import numpy as np
import pandas as pd

In [52]:
a=np.random.randint(1,11,10)
a

array([ 6, 10,  8,  1,  3,  1,  7,  6,  3,  8], dtype=int32)

In [53]:
label=[]
for i in range(1,11):
    label.append(i)
label

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
pd.Series(a,index=label)

1      6
2     10
3      8
4      1
5      3
6      1
7      7
8      6
9      3
10     8
dtype: int32

In [55]:
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
data

{'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Age': [28, 34, 29, 42],
 'City': ['New York', 'Paris', 'Berlin', 'London'],
 'Salary': [65000, 70000, 62000, 85000]}

In [59]:
label=np.arange(1,11)
label

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#create dataframe
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [98]:
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'London',78000]
]
data_list

[['John', 28, 'New York', 65000], ['Anna', 34, 'London', 78000]]

In [100]:
df_l=pd.DataFrame(data_list)
df_l

      0   1         2      3
0  John  28  New York  65000
1  Anna  34    London  78000

In [101]:
cols=["Name","Age","City","Salary"]
df_l=pd.DataFrame(data_list,columns=cols)
df_l

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34    London   78000

In [102]:
#selection and indexing of columns
df_l["Name"]   #ek row select krne k liye

0    John
1    Anna
Name: Name, dtype: object

In [103]:
#multipe rows k liye list bnao
df_l[["Name","City"]]

   Name      City
0  John  New York
1  Anna    London

In [104]:
#creating the colmn as designation
df_l["Designation"]=["Doctor","Teacher"]
df_l    #jitni rows hai utni value dal skte

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34    London   78000     Teacher

In [106]:
#remove column
df_l.drop("City",axis = 1)

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [107]:
df_l
#ab yaha remove krne k baad bhi ni hta column toh ab ham inplace use krenge proper delete krne k liye

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34    London   78000     Teacher

In [108]:
df_l.drop("City",axis = 1,inplace= True)
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [110]:
df_l.drop(["Age","Salary"],axis = 1)

   Name Designation
0  John      Doctor
1  Anna     Teacher

In [111]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [112]:
#selecting a row(we use loc(location) for rows)
df_l.loc[0]

Name             John
Age                28
Salary          65000
Designation    Doctor
Name: 0, dtype: object

In [113]:
df_l.loc[[0,1]]

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [114]:
#selectin subset rows and columns
df.loc[[0,1]][['Age','Salary']]

   Age  Salary
0   28   65000
1   34   70000

In [116]:
df_l.loc[1]

Name              Anna
Age                 34
Salary           78000
Designation    Teacher
Name: 1, dtype: object

In [122]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [125]:
df_l.loc[[0,1]][['Name','Designation']]

   Name Designation
0  John      Doctor
1  Anna     Teacher

In [127]:
df_l

   Name  Age  Salary Designation
0  John   28   65000      Doctor
1  Anna   34   78000     Teacher

In [129]:
#conditional selection
#find age whose age is above 30
df_l[df_l['Age']>30]

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [133]:
#find age whose is above 20 and they designation  teacher
# '&'-Mtlb AND '|'-mtlb OR
df_l[(df_l["Age"]>20 )&( df_l["Designation"]=='Teacher')]

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [132]:
#Advanced method
df_l.query("Age > 20 and Designation == 'Teacher'")

   Name  Age  Salary Designation
1  Anna   34   78000     Teacher

In [1]:
'''
Finding Missing data
Removing missing data
filling the missing data
'''

'\nFinding Missing data\nRemoving missing data\nfilling the missing data\n'

In [3]:
import numpy as np
import pandas as pd

In [8]:
#nan mtln nonevalue
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [17]:
#ham true false mei dekh lenge ki her rows mei nan value hai ki nhi using 'isna'
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [18]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [19]:
#kya sb mei null vale hau?
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [20]:
'''Removing works on rows'''
df.dropna()   #jis jsi mei null value hai hata do woh row

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
#thresh
df.dropna(thresh=3)    #atleast 3 none null val honi chahiye

In [ ]:
#filling the non value data

In [21]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [22]:
df.fillna(0)    #jaha nan hai waha 0

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [23]:
values={'A':1,'B':2,'C':3,'D':4}
df.fillna(value=values)

     A    B    C    D
0  1.0  2.0  1.0  1.0
1  2.0  2.0  2.0  4.0
2  1.0  3.0  3.0  4.0
3  4.0  4.0  3.0  4.0
4  5.0  5.0  3.0  5.0

In [24]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [25]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [42]:
import numpy as np
import pandas as pd

#mergingJoiningConcatination
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['Jon','Anha','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','HR']
})
salaries=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'salary':[60000,80000,65000,70000,np.nan],
    'bonus':[5000,1000,7000,8000,np.nan]
})

In [39]:
employees

   employee_id   name department
0            1    Jon         HR
1            2   Anha         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [28]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000   1000
2            3   65000   7000
3            4   70000   8000
4            5   90000  12000

In [31]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1    Jon         HR   60000   5000
1            2   Anha         IT   80000   1000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

In [34]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department  salary  bonus
0            1    Jon         HR   60000   5000
1            2   Anha         IT   80000   1000
2            3  Peter    Finance   65000   7000
3            4  Linda         IT   70000   8000
4            5    Bob         HR   90000  12000

In [2]:
import numpy as np
import pandas as pd

In [52]:
ar=np.random.randint(1,11,8)
ar

array([5, 4, 5, 9, 5, 7, 6, 4], dtype=int32)

In [53]:
ar1=pd.DataFrame({
    'employee_id':[ar[0],ar[1],ar[2],ar[3],ar[4],ar[5],ar[6],ar[7]],
    'Name':['Ram','Shyam','Ravi','Laksh','Rawan','Mohit','Dhruv','Ash'],
    'Salary':[65000,89000,78000,32000,43000,90000,88800,54000],})
ar1

   employee_id   Name  Salary
0            5    Ram   65000
1            4  Shyam   89000
2            5   Ravi   78000
3            9  Laksh   32000
4            5  Rawan   43000
5            7  Mohit   90000
6            6  Dhruv   88800
7            4    Ash   54000

In [51]:
r_b=np.random.randint(5000,10000,8)
bonus=pd.DataFrame(
    {
    'Bonus':r_b,
    'Name':['Ram','Shyam','Ravi','Laksh','Rawan','Mohit','Dhruv','Ash']
     }
)
bonus

   Bonus   Name
0   5359    Ram
1   8767  Shyam
2   6102   Ravi
3   5093  Laksh
4   7970  Rawan
5   5958  Mohit
6   8084  Dhruv
7   6678    Ash

In [54]:
pd.merge(ar1,bonus,on='Name',how='inner')

   employee_id   Name  Salary  Bonus
0            5    Ram   65000   5359
1            4  Shyam   89000   8767
2            5   Ravi   78000   6102
3            9  Laksh   32000   5093
4            5  Rawan   43000   7970
5            7  Mohit   90000   5958
6            6  Dhruv   88800   8084
7            4    Ash   54000   6678

In [3]:
import numpy as np
import pandas as pd

In [13]:
emplyee=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Anna','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','HR']
})

In [15]:
emplyee

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [14]:
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[56000,56890,90000,55500,23100],
    'bonus':[5000,6000,2000,9000,4554]
})

In [16]:
salaries

   employee_id  salary  bonus
0            1   56000   5000
1            2   56890   6000
2            3   90000   2000
3            6   55500   9000
4            7   23100   4554

In [18]:
pd.merge(emplyee,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   56000   5000
1            2   Anna         IT   56890   6000
2            3  Peter    Finance   90000   2000

In [21]:
pd.merge(emplyee,salaries,on='employee_id',how='outer')

   employee_id   name department   salary   bonus
0            1   John         HR  56000.0  5000.0
1            2   Anna         IT  56890.0  6000.0
2            3  Peter    Finance  90000.0  2000.0
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN
5            6    NaN        NaN  55500.0  9000.0
6            7    NaN        NaN  23100.0  4554.0

In [22]:
pd.merge(emplyee,salaries,on='employee_id',how='left')

   employee_id   name department   salary   bonus
0            1   John         HR  56000.0  5000.0
1            2   Anna         IT  56890.0  6000.0
2            3  Peter    Finance  90000.0  2000.0
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN

In [24]:
pd.merge(emplyee,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   56000   5000
1            2   Anna         IT   56890   6000
2            3  Peter    Finance   90000   2000
3            6    NaN        NaN   55500   9000
4            7    NaN        NaN   23100   4554

In [25]:
#concatenation
pd.concat([emplyee,salaries])

   employee_id   name department   salary   bonus
0            1   John         HR      NaN     NaN
1            2   Anna         IT      NaN     NaN
2            3  Peter    Finance      NaN     NaN
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN
0            1    NaN        NaN  56000.0  5000.0
1            2    NaN        NaN  56890.0  6000.0
2            3    NaN        NaN  90000.0  2000.0
3            6    NaN        NaN  55500.0  9000.0
4            7    NaN        NaN  23100.0  4554.0

In [27]:
#concatenation in rows
pd.concat([emplyee,salaries],axis=1)

   employee_id   name department  employee_id  salary  bonus
0            1   John         HR            1   56000   5000
1            2   Anna         IT            2   56890   6000
2            3  Peter    Finance            3   90000   2000
3            4  Linda         IT            6   55500   9000
4            5    Bob         HR            7   23100   4554

In [28]:
#joining 2 dataframe
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index=[1,2,3])
df2=pd.DataFrame({
    'score':[89,90,87]
},index=[2,3,4])

In [29]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [30]:
df2

   score
2     89
3     90
4     87

In [31]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   89.0
3  Charlie   90.0

In [32]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   89.0
3  Charlie   90.0
4      NaN   87.0

In [33]:
df2.join(df1)

   score     name
2     89      Bob
3     90  Charlie
4     87      NaN

In [34]:
'''Group by Aggregation'''

'Group by Aggregation'

In [35]:
import numpy as np
import pandas as pd

In [45]:
data={
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01',periods=8)
}
df=pd.DataFrame(data,index=[1,2,3,4,5,6,7,8])
df

  Category Store  Sales  Quantity       Date
1        A    S1    100        10 2023-01-01
2        B    S1    200        15 2023-01-02
3        A    S2    150        12 2023-01-03
4        B    S2    250        18 2023-01-04
5        A    S1    120         8 2023-01-05
6        B    S2    180        20 2023-01-06
7        A    S2    200        15 2023-01-07
8        B    S1    300        25 2023-01-08

In [49]:
#group by category and calculate the sum of sales
cat=df.groupby('Category')
cat
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
1        A    S1    100        10 2023-01-01
3        A    S2    150        12 2023-01-03
5        A    S1    120         8 2023-01-05
7        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
2        B    S1    200        15 2023-01-02
4        B    S2    250        18 2023-01-04
6        B    S2    180        20 2023-01-06
8        B    S1    300        25 2023-01-08

In [53]:
cat=df.groupby(['Category'])['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [52]:
#group by multiple columns
# group by category and store
cat=df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [54]:
#Aggregation
df['Sales'].mean()

np.float64(187.5)

In [57]:
df['Sales'].agg(['count','max'])       #only mode can't do

count      8
max      300
Name: Sales, dtype: int64

In [58]:
#PivotTables
import numpy as np
import pandas as pd

In [62]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df=pd.DataFrame(data)

df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    643     98   John  January      Q1
1  2023-01-02       B   West    728     98   Mary  January      Q1
2  2023-01-03       C  North    448     27    Bob  January      Q1
3  2023-01-04       D  South    474     24  Alice  January      Q1
4  2023-01-05       A   East    672     14   John  January      Q1
5  2023-01-06       B   West    526     37   Mary  January      Q1
6  2023-01-07       C  North    122     40    Bob  January      Q1
7  2023-01-08       D  South    205     29  Alice  January      Q1
8  2023-01-09       A   East    805     36   John  January      Q1
9  2023-01-10       B   West    172     31   Mary  January      Q1
10 2023-01-11       C  North    376     46    Bob  January      Q1
11 2023-01-12       D  South    314     67  Alice  January      Q1
12 2023-01-13       A   East    952     35   John  January      Q1
13 2023-01-14       B   West    629     39   Mary  January      Q1
14 2023-01-15       C  North    788     93    Bob  January      Q1
15 2023-01-16       D  South    590     93  Alice  January      Q1
16 2023-01-17       A   East    756     38   John  January      Q1
17 2023-01-18       B   West    155     56   Mary  January      Q1
18 2023-01-19       C  North    503     20    Bob  January      Q1
19 2023-01-20       D  South    132     48  Alice  January      Q1

In [63]:
#value ka mean aa ra
pd.pivot_table(df,values="Sales",index='Region',columns="Product")

Product      A      B      C      D
Region
East     765.6    NaN    NaN    NaN
North      NaN    NaN  447.4    NaN
South      NaN    NaN    NaN  343.0
West       NaN  442.0    NaN    NaN

In [67]:
pd.pivot_table(df,values="Sales",index='Region',columns="Product",fill_value="-",aggfunc="median")

Product      A      B      C      D
Region
East     756.0      -      -      -
North        -      -  448.0      -
South        -      -      -  314.0
West         -  526.0      -      -

In [69]:
#values whi lo jo numeric ho but index can different
pivot2=pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product",fill_value="-")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     765.6      -      -      -  44.2     -     -     -
North        -      -  447.4      -     -     -  45.2     -
South        -      -      -  343.0     -     -     -  52.2
West         -  442.0      -      -     -  52.2     -     -

In [74]:
#cross tab(yaha ham counting fx use krte rather than aggreagting fx)
pd.crosstab(df['Region'],df['Product'])     #counting function

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [78]:
import numpy as np
import pandas as pd

In [75]:
'''Operations'''

'Operations'

In [77]:
df1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [79]:
#Dataframes Basic operations
df1.shape

(5, 3)

In [80]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [81]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [82]:
df.describe()

                      Date       Sales      Units
count                   20   20.000000  20.000000
mean   2023-01-10 12:00:00  499.500000  48.450000
min    2023-01-01 00:00:00  122.000000  14.000000
25%    2023-01-05 18:00:00  286.750000  30.500000
50%    2023-01-10 12:00:00  514.500000  38.500000
75%    2023-01-15 06:00:00  686.000000  58.750000
max    2023-01-20 00:00:00  952.000000  98.000000
std                    NaN  253.246396  26.912089

In [83]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [84]:
#Dataframes applying function
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [87]:
#ab muje square krna
def sq(x):
    return x**2

In [88]:
df1["B"].apply(sq)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [89]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [91]:
#permanent change
df1["D"]=df1["B"].apply(sq)
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [93]:
df1["D"]=df1["B"].apply(lambda x:x**2)
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [ ]:
#finding data
'''
.csv=pd.read_csv('file.csv')
.excel(.xls,.xlsx)=pd.read_excel('file.xls')
.db,.sqlite(sqldb)=pd.read_sql(query,connection)
'''